# Default workflow: index genome FASTAs (gunzip + samtools + GATK + BWA).
# Run from repo root:
#   snakemake -s workflow/Snakefile --directory workflow --cores 4 -p --use-conda

configfile: "../config/config.yaml"
include: "rules/common.smk"

init_indexing(config)

wildcard_constraints:
    source="|".join(re.escape(s) for s in SOURCE_SET),
    assembly="|".join(re.escape(a) for a in ASSEMBLY_SET),


rule all:
    input:
        DONE,


rule decompress_genome:
    input:
        lambda wc: raw_path(genome_row(wc)),
    output:
        ref=f"{SRC}/{{source}}/{{assembly}}.fna",
    log:
        f"{LOG}/decompress_genome/{{source}}_{{assembly}}.log",
    shell:
        "mkdir -p $(dirname {output.ref}) && gzip -dc {input} > {output.ref} 2> {log}"


rule samtools_faidx:
    input:
        ref=rules.decompress_genome.output.ref,
    output:
        f"{SRC}/{{source}}/{{assembly}}.fna.fai",
    log:
        f"{LOG}/samtools_faidx/{{source}}_{{assembly}}.log",
    conda:
        "envs/ref.yaml",
    shell:
        "samtools faidx {input.ref} 2> {log}"


rule gatk_sequence_dictionary:
    input:
        ref=rules.decompress_genome.output.ref,
    output:
        f"{SRC}/{{source}}/{{assembly}}.dict",
    log:
        f"{LOG}/gatk_sequence_dictionary/{{source}}_{{assembly}}.log",
    conda:
        "envs/ref.yaml",
    shell:
        "gatk CreateSequenceDictionary -R {input.ref} -O {output} 2> {log}"


rule bwa_index:
    input:
        ref=rules.decompress_genome.output.ref,
    output:
        multiext(
            f"{SRC}/{{source}}/{{assembly}}.fna",
            ".amb",
            ".ann",
            ".bwt",
            ".pac",
        ),
    log:
        f"{LOG}/bwa_index/{{source}}_{{assembly}}.log",
    conda:
        "envs/ref.yaml",
    shell:
        "bwa index {input.ref} 2> {log}"


rule Trep_ref_indexing_done:
    input:
        expand(rules.samtools_faidx.output, zip, source=SOURCES, assembly=ASSEMBLIES),
        expand(rules.gatk_sequence_dictionary.output, zip, source=SOURCES, assembly=ASSEMBLIES),
        expand(rules.bwa_index.output, zip, source=SOURCES, assembly=ASSEMBLIES),
    output:
        DONE,
    shell:
        "touch {output}"
