# Index Trifolium repens genome FASTAs (NCBI download, gunzip, samtools, GATK, BWA).
# Run from repo root:
#   ./scripts/run_indexing.sh 4
# Setup: conda env create -f environment.yaml  (Snakemake only; tools via --use-conda)

configfile: "../config/config.yaml"
include: "rules/common.smk"


rule all:
    input:
        DONE,


rule download_genome:
    output:
        gz=lambda wc: raw_path(genome_row(wc)),
    log:
        f"{LOG}/download_genome/{{source}}_{{assembly}}.log",
    params:
        accession=lambda wc: accession(genome_row(wc)),
        script=str(DOWNLOAD_SCRIPT),
    conda:
        DATASETS_CONDA,
    shell:
        """
        if [[ -z "{params.accession}" ]]; then
          echo "No GenBank accession for {wildcards.source}/{wildcards.assembly}" >&2
          exit 1
        fi
        bash {params.script} {params.accession} {output.gz} {log}
        """


rule decompress_genome:
    input:
        gz=genome_gz_input,
    output:
        ref=f"{SRC}/{{source}}/{{assembly}}.fna",
    log:
        f"{LOG}/decompress_genome/{{source}}_{{assembly}}.log",
    shell:
        "mkdir -p $(dirname {output.ref}) && gzip -dc {input.gz} > {output.ref} 2> {log}"


rule samtools_faidx:
    input:
        ref=rules.decompress_genome.output.ref,
    output:
        f"{SRC}/{{source}}/{{assembly}}.fna.fai",
    log:
        f"{LOG}/samtools_faidx/{{source}}_{{assembly}}.log",
    conda:
        CONDA,
    shell:
        "samtools faidx {input.ref} 2> {log}"


rule gatk_sequence_dictionary:
    input:
        ref=rules.decompress_genome.output.ref,
    output:
        f"{SRC}/{{source}}/{{assembly}}.dict",
    log:
        f"{LOG}/gatk_sequence_dictionary/{{source}}_{{assembly}}.log",
    conda:
        CONDA,
    shell:
        "gatk CreateSequenceDictionary -R {input.ref} -O {output} 2> {log}"


rule bwa_index:
    input:
        ref=rules.decompress_genome.output.ref,
    output:
        multiext(
            f"{SRC}/{{source}}/{{assembly}}.fna",
            ".amb",
            ".ann",
            ".bwt",
            ".pac",
        ),
    log:
        f"{LOG}/bwa_index/{{source}}_{{assembly}}.log",
    conda:
        CONDA,
    shell:
        "bwa index {input.ref} 2> {log}"


rule indexing_done:
    input:
        indexing_done_inputs,
    output:
        DONE,
    shell:
        "touch {output}"
